### ISSUE TITLE
Issue with factions prefix

### ISSUE THREAD

**Issue by magnum4456789** [DRE2N/FactionsOne#13]
Firstly i don't speak English so i think that you are not going to understand anything.
I have an Issue with factions tag,i try lots of things but i don't get anything,heres a photo about it:
![image](https://cloud.githubusercontent.com/assets/13919017/16603701/8cea3122-431e-11e6-9e78-6c461660b3c6.png)
Here is other photo of my plugins:
![image](https://cloud.githubusercontent.com/assets/13919017/16603752/f755dc5a-431e-11e6-919e-ff31b75a1329.png)
I don't touch anything of the config,only chat set format "True".

**Comment by magnum4456789** [comment]
I have FactionsOne-v1.0-1.8.3

**Comment by Sataniel98** [comment]
Well, how do you want it to look like?

**Comment by magnum4456789** [comment]
With the faction prefix,the normal one.

**Comment by Sataniel98** [comment]
EssenitalsChat is probably overriding it. You could just remove it and make all channels with FactionChat instead.

**Comment by jtriskele** [comment]
![fquestions4](https://cloud.githubusercontent.com/assets/20294748/16708623/13256f1a-45c0-11e6-8367-f0fe32aaf40f.png)
You need to set the lines that I underlined to true in the Factions conf.json file. Your "chatsetformatto" line should look something like it does in the picture. Once you're done with that, you need to run the command /f reload on your server rather than restarting it. This should fix your problem. I have my chat set format to "{faction_relcolor}[{faction_tag_pr}]§f%s> %s" and a faction prefix would look like this on my server:
![fquestion5](https://cloud.githubusercontent.com/assets/20294748/16708653/f87b071e-45c0-11e6-9256-88e387ea0bf7.png)

If you want your faction prefix to look like it does on normal servers then you need to set your chat set format to: "{faction_relcolor}{faction_roleprefix}{faction_relcolor}{faction_tag_pr}§f%s> %s"
