### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by TheIronMinerLv** [DRE2N/FactionsOne#16]
Hello, for past few days server keep crashing after uknown amount of hours. I really don't know why, in this error is many plugins, someone told, that factions is main "problem", so please help!

Here is crash: http://pastebin.com/hBaCZjue

**Comment by Sataniel98** [comment]
Is this the full stacktrace?

**Comment by TheIronMinerLv** [comment]
What does that mean? I pasted full error, what I got in console.

**Comment by Sataniel98** [comment]
Indeed, it could be caused by an event only called at MONITOR. However, it's hard to reproduce it for me because it seems to occur just if multiple plugins do hacky stuff that mess up things. Would you please test this build and tell me if it works and if there are any new issues with the chat? http://feuerstern.bplaced.net/repo/io/github/dre2n/factionsone/archives/factionsone-1.3-SNAPSHOT-09.jar

**Comment by TheIronMinerLv** [comment]
My server is running more than 7hours, I'll test that version for few more hours, then I'll respond to this issue again...

BTW, now in console there is very weird formatting: http://prntscr.com/byn57k

**Comment by Sataniel98** [comment]
It seems I'll have to rewrite this to make it work perfectly. The in game chat is not affected?

**Comment by TheIronMinerLv** [comment]
Nope, that only shows up in console

**Comment by TheIronMinerLv** [comment]
Hello, after about 14H there is a new crash, this seems like a little bit different, I can't tell if Factions is the main cause... http://pastebin.com/nqcnemi5

**Comment by Sataniel98** [comment]
Well, it doesn't even appear in the stacktrace, so I don't think it's the reason.
