### ISSUE TITLE
Faction Name In Chat

### ISSUE THREAD

**Issue by The-Last-Centurion** [DRE2N/FactionsOne#28]
I added one of the faction name tags to the essentials chat format, when not in a faction the chat appears as [this](http://imgur.com/a/i3xcf). When in a faction, it looks fine, but there's a gap after the tag that I cannot remove, making the right angle bracket look weird.

**Comment by Sataniel98** [comment]
Can't really spot the issue in this screenshot. The plus is the usual prefix if the player is neither recruit or officer / leader. You can set it to nothing in the conf.json if you want to (the command won't work because MC doesn't like empty arguments). The space after the tag is intended sothat there is no space between the prefix if you don't have a title (e.g. "**Sataniel: Text") but if you have one (e.g. "**King Sataniel: Text").

**Comment by The-Last-Centurion** [comment]
I'm pretty sure the issue is because all players become a member of wilderness on join. No idea how to fix that as I don't have much knowledge in Java.

**Comment by Sataniel98** [comment]
That's exactly how the plugin works.

**Comment by The-Last-Centurion** [comment]
I'll just remove the recruit/member indication.

**Comment by Sataniel98** [comment]
There are a few addons around that do this if I remember it correctly.
